#!/usr/bin/env bun
export {}
const base = "https://rest.arbeitsagentur.de/jobboerse/jobsuche-service";
const headers = { "X-API-Key": "jobboerse-jobsuche", Accept: "application/json" };
type Flags = Record<string, string | boolean>;
function fail(error: string, code: string): never { process.stderr.write(JSON.stringify({ error, code }) + "\n"); process.exit(1); }
function parse(args: string[]) { const positional: string[] = []; const flags: Flags = {}; for (let i = 0; i < args.length; i++) { const arg = args[i]; if (!arg.startsWith("-")) { positional.push(arg); continue; } const raw = arg.replace(/^-+/, ""); const key = raw === "q" ? "query" : raw === "l" ? "location" : raw; const next = args[i + 1]; flags[key] = next && !next.startsWith("-") ? (i++, next) : true; } return { positional, flags }; }
function str(v: string | boolean | undefined) { return typeof v === "string" ? v : undefined; }
function positive(name: string, v: string | boolean | undefined, fallback: number) { if (v === undefined) return fallback; const n = Number(str(v)); if (!Number.isInteger(n) || n < 1) fail(`--${name} must be a positive integer`, "BAD_ARG"); return n; }
async function get(path: string) { const response = await fetch(base + path, { headers, signal: AbortSignal.timeout(15000) }); if (response.status === 404) return null; if (!response.ok) fail(`Arbeitsagentur API request failed: ${response.status}`, "API_ERROR"); return response.json() as Promise<Record<string, unknown>>; }
function normalize(job: Record<string, unknown>) { const id = String(job.refnr ?? job.referenznummer ?? "") || null; const locations = job.stellenlokationen as Array<Record<string, unknown>> | undefined; const address = locations?.[0]?.adresse as Record<string, unknown> | undefined; const place = String(address?.ort ?? "") || null; const url = String(job.externeUrl ?? job.externeURL ?? job.externalUrl ?? "") || (id ? `https://www.arbeitsagentur.de/jobsuche/jobdetail/${encodeURIComponent(id)}` : null); return { id, title: String(job.beruf ?? job.stellenangebotsTitel ?? "") || null, company: String(job.arbeitgeber ?? job.firma ?? "") || null, location: place, date: String(job.aktuelleVeroeffentlichungsdatum ?? job.datumErsteVeroeffentlichung ?? "") || null, url }; }
function output(rows: ReturnType<typeof normalize>[], fmt: string, page: number) { if (!["json", "table", "plain"].includes(fmt)) fail("--format must be json, table, or plain", "BAD_ARG"); if (fmt === "json") { console.log(JSON.stringify({ meta: { count: rows.length, page }, results: rows }, null, 2)); return; } for (const row of rows) console.log(fmt === "plain" ? `${row.title ?? "(untitled)"}\n  ${row.company ?? "—"} · ${row.location ?? "—"}\n  ${row.url ?? "—"}\n` : `${(row.id ?? "—").padEnd(26)} ${(row.title ?? "—").slice(0, 45)} | ${row.company ?? "—"} | ${row.location ?? "—"}`); }
async function search(flags: Flags) { const query = str(flags.query); if (!query) fail("search requires --query/-q", "MISSING_REQUIRED"); const thesis = flags.thesis === true; const page = positive("page", flags.page, 1); const params = new URLSearchParams({ was: query, page: String(page), size: String(positive("limit", flags.limit, thesis ? 12 : 20)), veroeffentlichtseit: String(positive("jobage", flags.jobage, thesis ? 14 : 100)) }); if (str(flags.location)) params.set("wo", str(flags.location)!); if (thesis) params.set("angebotsart", "34"); const data = await get(`/pc/v6/jobs?${params}`); const offers = Array.isArray(data?.ergebnisliste) ? data!.ergebnisliste : []; output(offers.filter((x): x is Record<string, unknown> => !!x && typeof x === "object").map(normalize), str(flags.format) ?? "json", page); }
async function detail(id: string, flags: Flags) { if (!id) fail("detail requires a reference number", "MISSING_REQUIRED"); const data = await get(`/pc/v4/jobdetails/${encodeURIComponent(Buffer.from(id).toString("base64"))}`); if (!data) fail("job not found", "NOT_FOUND"); console.log(JSON.stringify(data, null, 2)); }
const parsed = parse(process.argv.slice(2)); if (parsed.positional[0] === "search") await search(parsed.flags); else if (parsed.positional[0] === "detail") await detail(parsed.positional[1] ?? "", parsed.flags); else fail("use: search --query <text> [--thesis] or detail <reference-number>", "BAD_CMD");
