#!/usr/bin/env bun
export {};

type Flags = Record<string, string | boolean>;
type ApiRecord = Record<string, unknown>;
type Job = { id: string; title: string | null; company: string | null; location: string | null; published: string | null; deadline: string | null; url: string | null; sourceUrl: string | null };
const base = "https://jobsearch.api.jobtechdev.se";

function fail(error: string, code: string): never { process.stderr.write(JSON.stringify({ error, code }) + "\n"); process.exit(1); }
function parse(args: string[]) { const positional: string[] = []; const flags: Flags = {}; for (let i = 0; i < args.length; i++) { const argument = args[i]; if (!argument.startsWith("-")) { positional.push(argument); continue; } const raw = argument.replace(/^-+/, ""); const key = raw === "q" ? "query" : raw === "l" ? "location" : raw; const next = args[i + 1]; flags[key] = next && !next.startsWith("-") ? (i++, next) : true; } return { positional, flags }; }
function text(value: unknown) { return typeof value === "string" && value.trim() ? value : null; }
function stringFlag(value: string | boolean | undefined) { return typeof value === "string" ? value : undefined; }
function positive(name: string, value: string | boolean | undefined, fallback: number, maximum: number) { if (value === undefined) return fallback; const number = Number(stringFlag(value)); if (!Number.isInteger(number) || number < 1 || number > maximum) fail(`--${name} must be an integer from 1 to ${maximum}`, "BAD_ARG"); return number; }
function object(value: unknown): ApiRecord { return value && typeof value === "object" && !Array.isArray(value) ? value as ApiRecord : {}; }
function normalize(record: ApiRecord): Job { const employer = object(record.employer); const address = object(record.workplace_address); const application = object(record.application_details); const external = text(application.url); return { id: String(record.id ?? ""), title: text(record.headline), company: text(employer.name), location: text(address.city) ?? text(address.municipality), published: text(record.publication_date), deadline: text(record.application_deadline), url: external ?? text(record.webpage_url), sourceUrl: text(record.webpage_url) }; }
function recentDate(days: number) { const date = new Date(); date.setUTCDate(date.getUTCDate() - days); return date.toISOString().slice(0, 10); }
async function get(path: string) { const response = await fetch(base + path, { headers: { Accept: "application/json" }, signal: AbortSignal.timeout(15_000) }); if (response.status === 404) return null; if (!response.ok) fail(`Arbetsförmedlingen request failed: ${response.status}`, "API_ERROR"); return response.json() as Promise<ApiRecord>; }
function output(rows: Job[], format: string, meta: Record<string, unknown>) { if (!['json', 'table', 'plain'].includes(format)) fail("--format must be json, table, or plain", "BAD_ARG"); if (format === "json") { console.log(JSON.stringify({ meta: { count: rows.length, ...meta }, results: rows }, null, 2)); return; } for (const job of rows) console.log(format === "plain" ? `${job.title ?? "(untitled)"}\n  ${job.company ?? "—"} · ${job.location ?? "—"}\n  ${job.url ?? "—"}\n` : `${job.id.padEnd(12)} ${(job.title ?? "—").slice(0, 44).padEnd(46)} | ${job.company ?? "—"} | ${job.location ?? "—"}`); }
async function search(flags: Flags) { const query = stringFlag(flags.query); if (!query) fail("search requires --query/-q", "MISSING_REQUIRED"); const thesis = flags.thesis === true; const jobage = positive("jobage", flags.jobage, thesis ? 14 : 100, 365); const params = new URLSearchParams({ q: query, limit: String(positive("limit", flags.limit, thesis ? 12 : 20, 20)), "published-after": recentDate(jobage) }); if (stringFlag(flags.location)) params.set("q", `${query} ${stringFlag(flags.location)}`); const data = await get(`/search?${params}`); const hits = Array.isArray(data?.hits) ? data.hits : []; output(hits.filter((item): item is ApiRecord => !!item && typeof item === "object" && !Array.isArray(item)).map(normalize), stringFlag(flags.format) ?? "json", { query, location: stringFlag(flags.location) ?? null, jobage }); }
async function detail(id: string) { if (!/^\d+$/.test(id)) fail("detail requires a numeric JobSearch ad ID", "MISSING_REQUIRED"); const data = await get(`/ad/${encodeURIComponent(id)}`); if (!data) fail("job not found", "NOT_FOUND"); console.log(JSON.stringify(data, null, 2)); }
const parsed = parse(process.argv.slice(2)); if (parsed.positional[0] === "search") await search(parsed.flags); else if (parsed.positional[0] === "detail") await detail(parsed.positional[1] ?? ""); else fail("use: search --query <text> [--thesis] or detail <ad-id>", "BAD_CMD");
