#!/usr/bin/env bun
export {};

type Flags = Record<string, string | boolean>;
type ApiJob = { id?: number; title?: string | null; employer?: string | null; location?: string | null; deadline?: string | null; link?: string | null; summary?: string | null; jobDuration?: string | null };
type Job = { id: string; title: string | null; company: string | null; location: string | null; deadline: string | null; duration: string | null; url: string | null; summary: string | null };
const apiBase = "https://publicapi.jobbnorge.no/v1";
const detailBase = "https://www.jobbnorge.no/ledige-stillinger/stilling/";

function fail(error: string, code: string): never { process.stderr.write(JSON.stringify({ error, code }) + "\n"); process.exit(1); }
function parse(args: string[]) { const positional: string[] = []; const flags: Flags = {}; for (let i = 0; i < args.length; i++) { const argument = args[i]; if (!argument.startsWith("-")) { positional.push(argument); continue; } const raw = argument.replace(/^-+/, ""); const key = raw === "q" ? "query" : raw === "l" ? "location" : raw; const next = args[i + 1]; flags[key] = next && !next.startsWith("-") ? (i++, next) : true; } return { positional, flags }; }
function text(value: unknown) { return typeof value === "string" && value.trim() ? value.trim() : null; }
function stringFlag(value: string | boolean | undefined) { return typeof value === "string" ? value : undefined; }
function positive(name: string, value: string | boolean | undefined, fallback: number, maximum: number) { if (value === undefined) return fallback; const number = Number(stringFlag(value)); if (!Number.isInteger(number) || number < 1 || number > maximum) fail(`--${name} must be an integer from 1 to ${maximum}`, "BAD_ARG"); return number; }
function normalize(record: ApiJob): Job { return { id: String(record.id ?? ""), title: text(record.title), company: text(record.employer), location: text(record.location), deadline: text(record.deadline), duration: text(record.jobDuration), url: text(record.link), summary: text(record.summary) }; }
async function request(url: string) { const response = await fetch(url, { headers: { Accept: "application/json, text/html" }, signal: AbortSignal.timeout(15_000) }); if (response.status === 404) return null; if (!response.ok) fail(`Jobbnorge request failed: ${response.status}`, "API_ERROR"); return response; }
function output(rows: Job[], format: string, meta: Record<string, unknown>) { if (!['json', 'table', 'plain'].includes(format)) fail("--format must be json, table, or plain", "BAD_ARG"); if (format === "json") { console.log(JSON.stringify({ meta: { count: rows.length, ...meta }, results: rows }, null, 2)); return; } for (const job of rows) console.log(format === "plain" ? `${job.title ?? "(untitled)"}\n  ${job.company ?? "—"} · ${job.location ?? "—"}\n  ${job.url ?? "—"}\n` : `${job.id.padEnd(10)} ${(job.title ?? "—").slice(0, 44).padEnd(46)} | ${job.company ?? "—"} | ${job.location ?? "—"}`); }
async function search(flags: Flags) { const query = stringFlag(flags.query); if (!query) fail("search requires --query/-q", "MISSING_REQUIRED"); const thesis = flags.thesis === true; const params = new URLSearchParams({ term: stringFlag(flags.location) ? `${query} ${stringFlag(flags.location)}` : query, results: String(positive("limit", flags.limit, thesis ? 12 : 20, 25)), page: String(positive("page", flags.page, 1, 50)), orderby: "Published", period: thesis ? "Week" : "All" }); const response = await request(`${apiBase}/Jobs?${params}`); if (!response) fail("listing page not found", "NOT_FOUND"); const data = await response.json() as unknown; if (!Array.isArray(data)) fail("unexpected Jobbnorge response", "UNEXPECTED_RESPONSE"); output(data.filter((job): job is ApiJob => !!job && typeof job === "object").map(normalize), stringFlag(flags.format) ?? "json", { query, location: stringFlag(flags.location) ?? null, period: thesis ? "Week" : "All" }); }
const parsed = parse(process.argv.slice(2)); if (parsed.positional[0] === "search") await search(parsed.flags); else fail("use: search --query <text> [--thesis]", "BAD_CMD");
